In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
model.get_weights()

[array([[-1.1993455 ,  0.08637357],
        [-1.1246998 , -0.9208051 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.11780477],
        [0.4977553 ]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([0.,0.],dtype=np.float32),np.array([[0.1],[0.1]],dtype=np.float32),np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 0.6943
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6939
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6942
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6940
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6938
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6939
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 0.6937
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6938
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6937
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 0.6937
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6937
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6936
Epoch 13/75
4/4 [==============================] - 0s 3ms/step - loss: 0.

In [14]:
model.make_predict_function

<bound method Model.make_predict_function of <keras.src.engine.sequential.Sequential object at 0x79d1c367f1f0>>